#!/bin/bash

file=zoo_staff_directory.csv
read -p "what is your password: " password
tail -n +2 $file | while IFS=, read -r name username department birthday age pronouns; do

  uid="username"

ldapdelete -w $password -D "cn=admin,dc=zoo,dc=local" "uid=$uid,cn=users,dc=zoo,dc=local"
done