#!/bin/bash

#set the name of the csv file to read
file="zoo_staff_directory.csv"
#set's user password
read -s -p "what is the users password? " users_password
echo
#asks for your ldap password
read -s -p "whats your ldap password: " passwd
echo

# Define a starting UID number (if you need to customize this, set it accordingly)
uid_start=1001

# Read the CSV file line by line, skip header (first line)
tail -n +2 $file | while IFS=, read -r name username department dob age pronouns; do
    # Generate UID number based on the start point and the line number

    uid_number=$((uid_start++))

    # Extract first and last name
first_name=$(echo $name | cut -d' ' -f1)
last_name=$(echo $name | cut -d' ' -f2)

password=$(sudo slappasswd -s $users_password)

# Prepare LDAP entry
dn="uid=$username,cn=users,dc=zoo,dc=local"
cn="$first_name $last_name"
sn="$last_name"
uid="$username"

    # Construct LDAP entry in LDIF format
cat <<EOF > /ldap-setup/BashScript/user.ldif
dn: $dn
objectClass: inetOrgPerson
objectClass: posixAccount
objectClass: shadowAccount
uid: $uid
cn: $cn
sn: $sn
uidNumber: $uid_number
gidNumber: 1001
homeDirectory: /home/$username
loginShell: /bin/bash
gecos: $first_name, $dob, $age, $pronouns
userPassword: $password

EOF

    # Add the entry to LDAP (replace with the correct ldapadd command)
    ldapadd -x -D "cn=admin,dc=zoo,dc=local" -w $passwd -f user.ldif

    # Clean up temporary LDIF file
   
done





#This script makes users. 
#It reads the csv file because of the tail command and it skips the first line which is often headers.
#It asks me for my ldap password so it can add all the users without me manually typing it out of each user.
#It asks me for the password the users should have and it hashes them